name: Swift Testing

on:
  pull_request:
    paths:
      - '.github/workflows/swift-testing.yaml'
      - 'api/**/*.swift'

jobs:
  small:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: swift-build-package-resolved-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Package.resolved') }}
          path: ${{ github.workspace }}/.build

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"

      - run: swift build

      - run: swift test